#!/usr/bin/env ruby

# $:.unshift File.expand_path('../../lib', __FILE__)
require "bundler/setup"
require "sugoi_iko_yo_log_fetcher_ruby"

cli = SugoiIkoYoLogFetcherRuby.build_cli(ARGV)
if cli.valid?
  begin
    cli.download!
  rescue => e
    puts e.message
    puts e.backtrace.join("\n")
    exit(1)
  end
else
  puts cli.message
  exit(1)
end
